# Generated by Django 4.1.7 on 2023-04-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RFID',
            new_name='Spaces',
        ),
        migrations.RenameField(
            model_name='spaces',
            old_name='RFID',
            new_name='Username',
        ),
    ]
